# Generated by Django 5.0.3 on 2024-03-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_admininput_alter_acceptscore_admin_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininput',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
